set lines 300
col USERNAME format a20
col PROGRAM format a40
col STATS format a10
col LOGON_TIME format a30
SELECT SID, SERIAL#, USERNAME, PROGRAM, BLOCKING_SESSION, 'Waiter' STATS, TO_CHAR(LOGON_TIME, 'DD/MM hh24:mi') LOGON_TIME FROM v$session
WHERE SID IN (SELECT BLOCKING_SESSION FROM V$SESSION WHERE BLOCKING_SESSION is not null)
UNION
select SID, SERIAL#, USERNAME, PROGRAM, BLOCKING_SESSION, 'Holder' STATS, TO_CHAR(LOGON_TIME, 'DD/MM hh24:mi') LOGON_TIME FROM v$session
WHERE BLOCKING_SESSION is not null
ORDER BY STATS DESC;