
Below script can be used to check Active Transactions in Oracle Database.

SET COLSEP '|'
COLUMN USERNAME FORMAT A15
COLUMN MACHINE FORMAT A25
COLUMN OSUSER FORMAT A15
COLUMN SID FORMAT 9999
COLUMN SPID FORMAT 99999
COLUMN STATUS FORMAT A15
SET LINESIZE 140

SET VERIFY OFF
SELECT S.SID,S.SERIAL#,P.SPID "SPID",S.USERNAME,S.STATUS,S.OSUSER,S.MACHINE,t.ses_addr
FROM V$SESSION S,V$PROCESS p,v$transaction t
WHERE S.PADDR=P.ADDR
AND S.USERNAME IS NOT NULL
AND S.STATUS='ACTIVE'
and t.ses_addr=s.saddr
ORDER BY S.USERNAME;

