###### Alterar opes de AUTOEXTEND OU MAXSIZE
ALTER DATABASE DATAFILE 'F:\oradata\live\Mydb02.ora' AUTOEXTEND ON|OFF MAXSIZE 32000M;



ALTER DATABASE DATAFILE '/ora/IOOEMRL/data04/users01.dbf' AUTOEXTEND ON MAXSIZE 200M;

