###### Add data file
Alter Tablespace SS64 ADD DATAFILE 'T:\oradata\live\Data02.DBF' SIZE 1500M;

ALTER TABLESPACE <name> ADD DATAFILE '/ora/POSMSEA/data03/tools02.dbf' SIZE 1000M AUTOEXTEND ON MAXSIZE 2000M;

ALTER TABLESPACE DAT_TNM ADD DATAFILE '/oradata/bnd01pz0/dat_tnm05.dbf' SIZE 2000M;

ALTER TABLESPACE MGMT_TABLESPACE ADD DATAFILE '/ora/IOOEMRL/data02/mgmt02.dbf' SIZE 2G;

ALTER TABLESPACE sysaux ADD DATAFILE '+disk_group_1' SIZE 100M;

ALTER DATABASE DATAFILE '+DATA1/dbname/datafile/audit.259.668957419' RESIZE 150M;



ALTER TABLESPACE TEMP ADD DATAFILE '+DATA2' SIZE 5GB AUTOEXTEND ON NEXT 500M MAXSIZE 100M;


ALTER TABLESPACE TEMP ADD TEMPFILE '+DATA2' SIZE 5G AUTOEXTEND ON NEXT 500M MAXSIZE 32768 M;




#Exemplo de criao de tablespace

CREATE TABLESPACE my_ts DATAFILE '+disk_group_1' SIZE 100M AUTOEXTEND ON;


