CREATE OR REPLACE PROCEDURE INDEX_DDL_GENERATOR(P_USERNAME IN VARCHAR2) IS
-------------------------------------------------
-- To auto-generate indexes DDL
--
-- emao Nov 14,2003
--
--------------------------------------------------

CURSOR C_INDEX IS
SELECT 'CREATE '||DECODE(INDEX_TYPE,'NORMAL',UNIQUENESS, INDEX_TYPE)||'
INDEX '||OWNER||'.'||INDEX_NAME||' ON '||OWNER||'.'||TABLE_NAME I_HEADER,
'TABLESPACE '||TABLESPACE_NAME||' STORAGE ( INITIAL '|| INITIAL_EXTENT/1024
|| 'K NEXT '|| NEXT_EXTENT/1024 ||'K );'
I_TAIL, TABLE_NAME, INDEX_NAME
FROM SYS.DBA_INDEXES
WHERE OWNER= P_USERNAME
AND INDEX_TYPE IN ('NORMAL','BITMAP');

R_INDEX C_INDEX%ROWTYPE;

CURSOR C_IND_COL(P_TABLE_NAME VARCHAR2, P_INDEX_NAME VARCHAR2) IS
SELECT COLUMN_NAME||' '||DESCEND COLUMN_NAME, COLUMN_POSITION
FROM SYS.DBA_IND_COLUMNS
WHERE INDEX_OWNER=P_USERNAME
AND TABLE_NAME=P_TABLE_NAME
AND INDEX_NAME=P_INDEX_NAME
ORDER BY COLUMN_POSITION;

R_IND_COL C_IND_COL%ROWTYPE;

V_COL_STR VARCHAR2(1024);

BEGIN

OPEN C_INDEX;
LOOP
FETCH C_INDEX INTO R_INDEX;
EXIT WHEN C_INDEX%NOTFOUND;

V_COL_STR := ' ';
OPEN C_IND_COL(R_INDEX.TABLE_NAME,R_INDEX.INDEX_NAME);
LOOP

FETCH C_IND_COL INTO R_IND_COL;
EXIT WHEN C_IND_COL%NOTFOUND;
IF C_IND_COL%ROWCOUNT = 1 THEN
V_COL_STR := R_IND_COL.COLUMN_NAME;
ELSE
V_COL_STR := V_COL_STR||', '||R_IND_COL.COLUMN_NAME;
END IF ;
--DBMS_OUTPUT.PUT_LINE(V_COL_STR);

END LOOP;
CLOSE C_IND_COL;

DBMS_OUTPUT.PUT_LINE( R_INDEX.I_HEADER||'( '||V_COL_STR||' )'||CHR(10)||R_INDEX.I_TAIL);
DBMS_OUTPUT.PUT_LINE(CHR(10));
END LOOP;
CLOSE C_INDEX;

END;
/

SET SERVEROUT ON SIZE 999999
SPOOL INDEX_DDL.SQL
EXEC INDEX_DDL_GENERATOR('&schema_name');
SPOOL OFF 