##ADMIN_RESTRICTIONS_LISTENER = on
#Settings to enable listener tracing SR 3-10291367751
DIAG_ADR_ENABLED_LISTENER=OFF
LOG_DIRECTORY_LISTENER=<log directory>
LOG_FILE_LISTENER=<log file name>
LOGGING_LISTENER = ON
TRACE_LEVEL_LISTENER = 16
TRACE_FILE_LISTENER = <trace file name>
TRACE_DIRECTORY_LISTENER = <trace directory>
TRACE_TIMESTAMP_LISTENER = ON