
col segment_name format a30
col segment_type format a15
set lines 1000 pages 200
select A.SEGMENT_NAME, A.SEGMENT_TYPE, A.TABLESPACE_NAME, B.COMPRESSION,B.NUM_ROWS,B.LAST_ANALYZED,A.BYTES/1024/1024/1024 "SIZE (GB)"
FROM DBA_SEGMENTS A, DBA_TABLES B
WHERE SEGMENT_NAME IN (
'SWWSWPRET','SAPWLMONI','CE4GG01_ACCT','MLCRP','STXH','VBPA','LTAP','STXL',
'CE1GG01','ZMMTABKPF','ZFST098','ZFST046','AFRU','COBK','BAL_INDX','COSP', 
'MLIT','SWP_HEADER','RESB','CKMLCR','ZFST009','REGUH','AFFV','VBUP',  
'SWWRUNMETH','BKPF','BSAD','VBEP','AFVC','VBRP','JEST','VBFA', 
'ZSDTOCL','BALHDR','CKIS','AFVV','MONI','MLCR','BSAS','SWP_NODEWI',  
'ZCRTSLG','COEP','MSEG','SWWBINDEF','ZASFELOGBKP','SWWWIRET','VBAP','LIPS',       
'SWWWIHEAD','SWW_CONT','SWPNODELOG','CDHDR','INDX','/IBMMON/ITM_STAT','GLPCA','SWW_CONTOB',  
'TST03','SWPSTEPLOG','BSIS','SWWLOGHIST','BALDAT')
AND A.SEGMENT_NAME = B.TABLE_NAME
AND A.OWNER = B.OWNER
ORDER BY A.BYTES/1024/1024/1024 DESC
/

select B.TABLE_NAME,A.SEGMENT_NAME,A.SEGMENT_TYPE, A.TABLESPACE_NAME, B.COMPRESSION, B.LAST_ANALYZED,b.BLEVEL,B.LEAF_BLOCKS,B.DISTINCT_KEYS,B.NUM_ROWS,A.BYTES/1024/1024/1024 "SIZE (GB)"
FROM DBA_SEGMENTS A, DBA_INDEXES B
WHERE SEGMENT_NAME IN (
'DMS_CONT1_CD1~0','CDHDR~Z01','CDHDR~0','CDHDR~Z03',
'APQD~0','SOST~0','CE1GOPC~3','SOOS~REC','SOOS~A','SOES~A',
'BCSD_ENVID~0','SOST~REC','BCSD_ENVID~ENV','BCST_RE~0',
'SOOD~OWN','SWNCMONI~0','ETXDCJ~0','SOST~SND','SOST~MES',
'SOOS~SND','SOST~DIR','BALHDR~2','SWWOUTBOX~002','/SYCLO/STOCK_EX~S2',
'RESB~Z01','BCST_SR~IN1','COFP~M','J_1BNFLIN~H0F','SWWUSERWI~0'
)
AND A.SEGMENT_NAME = B.INDEX_NAME
AND A.OWNER = B.OWNER
ORDER BY 1
/

ENABLE ROW MOVEMENT

select 'alter table '||table_name||' enable row movement;'
from dba_tables
where table_name in (
'SWWSWPRET','SAPWLMONI','CE4GG01_ACCT','MLCRP','STXH','VBPA','LTAP','STXL',
'CE1GG01','ZMMTABKPF','ZFST098','ZFST046','AFRU','COBK','BAL_INDX','COSP', 
'MLIT','SWP_HEADER','RESB','CKMLCR','ZFST009','REGUH','AFFV','VBUP',  
'SWWRUNMETH','BKPF','BSAD','VBEP','AFVC','VBRP','JEST','VBFA', 
'ZSDTOCL','BALHDR','CKIS','AFVV','MONI','MLCR','BSAS','SWP_NODEWI',  
'ZCRTSLG','COEP','MSEG','SWWBINDEF','ZASFELOGBKP','SWWWIRET','VBAP','LIPS',       
'SWWWIHEAD','SWW_CONT','SWPNODELOG','CDHDR','INDX','/IBMMON/ITM_STAT','GLPCA','SWW_CONTOB',  
'TST03','SWPSTEPLOG','BSIS','SWWLOGHIST','BALDAT');

SHRINK SPACE ON TABLES:

select 'alter table '||table_name||' shrink space cascade;'
from dba_tables
where table_name in (
'SWWSWPRET','SAPWLMONI','CE4GG01_ACCT','MLCRP','STXH','VBPA','LTAP','STXL',
'CE1GG01','ZMMTABKPF','ZFST098','ZFST046','AFRU','COBK','BAL_INDX','COSP', 
'MLIT','SWP_HEADER','RESB','CKMLCR','ZFST009','REGUH','AFFV','VBUP',  
'SWWRUNMETH','BKPF','BSAD','VBEP','AFVC','VBRP','JEST','VBFA', 
'ZSDTOCL','BALHDR','CKIS','AFVV','MONI','MLCR','BSAS','SWP_NODEWI',  
'ZCRTSLG','COEP','MSEG','SWWBINDEF','ZASFELOGBKP','SWWWIRET','VBAP','LIPS',       
'SWWWIHEAD','SWW_CONT','SWPNODELOG','CDHDR','INDX','/IBMMON/ITM_STAT','GLPCA','SWW_CONTOB',  
'TST03','SWPSTEPLOG','BSIS','SWWLOGHIST','BALDAT');


